#ifndef VERIFIED_PUZZLES_H
#define VERIFIED_PUZZLES_H

#include "puzzle_types.h"

#define VERIFIED_PUZZLE_COUNT 20

typedef struct {
    int optimal_mirrors;
    int sensor_count;
    Cell puzzle[INIT_ROWS][INIT_COLS];
    Cell solution[INIT_ROWS][INIT_COLS];
} VerifiedPuzzle;

static const VerifiedPuzzle VERIFIED_PUZZLES[VERIFIED_PUZZLE_COUNT] = {
    {
        .optimal_mirrors = 7,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 3}},
            {{SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {LASER, MIRROR_NONE, 3}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {SENSOR, MIRROR_NONE, 3}},
            {{SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 7,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {SENSOR, MIRROR_NONE, 0}, {SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {SENSOR, MIRROR_NONE, 0}, {SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 7,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}},
            {{LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}},
            {{LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 7,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 7,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {LASER, MIRROR_NONE, 1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 3}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {LASER, MIRROR_NONE, 1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 5,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {SENSOR, MIRROR_NONE, 2}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {SENSOR, MIRROR_NONE, 2}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 5,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {LASER, MIRROR_NONE, 1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 5,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 3}, {LASER, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_LEFT, -1}, {LASER, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 3}, {LASER, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 5,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 3}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}},
            {{SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 3}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}},
            {{SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 5,
        .sensor_count = 4,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {LASER, MIRROR_NONE, 3}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {LASER, MIRROR_NONE, 3}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {LASER, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 3}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_LEFT, -1}, {LASER, MIRROR_NONE, 2}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 4,
        .sensor_count = 3,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {LASER, MIRROR_NONE, 2}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 4,
        .sensor_count = 3,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {LASER, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {SENSOR, MIRROR_NONE, 1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 4,
        .sensor_count = 3,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 4,
        .sensor_count = 3,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 4,
        .sensor_count = 3,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 2}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 2}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 2,
        .sensor_count = 2,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 2,
        .sensor_count = 2,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 2,
        .sensor_count = 1,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 2,
        .sensor_count = 2,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_LEFT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
    {
        .optimal_mirrors = 2,
        .sensor_count = 1,
        .puzzle = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
        .solution = {
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {SENSOR, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_RIGHT, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}},
            {{EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {LASER, MIRROR_NONE, 0}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}, {EMPTY, MIRROR_NONE, -1}}
        },
    },
};

#endif
